export const regrasPorTipo = {
  proposta: {
    usarCalculo: true,
    usarCampoPadrao: true,
    lancamentoForaDto: true,
    pixPagamentoForaDto: true,
    contaPagamentoForaDto: true,
    incluir: [],
    remover: [
      'DtPrimeiroVencto',
      'PercIOF',
      'PercIOFAdicional',
      'PercIndiceFinanceiro',
      'PercRetencao',
      'PercSeguroMensal1',
      'PercSeguroMensal2',
      'TipoIndiceFinanceiro',
      'VlrTac',
      'VlrParcela',
      'VlrSolicitado',
      'VlrAcessorios',
      'VlrAvaliacao',
      'VlrBlindagem',
      'VlrBoleto',
      'VlrCertiDocs',
      'VlrCorban',
      'VlrDespachante',
      'VlrDespesasAF',
      'VlrEntrada',
      'VlrEntradaParcelada',
      'VlrEntradaTradeIn',
      'VlrIOF',
      'VlrOutrasDespesas',
      'VlrOutrosServicos',
      'VlrProdutoBem',
      'VlrRegistro',
      'VlrRegistroCartorio',
      'VlrRetencao',
      'VlrSeguro',
      'VlrSeguroMensal1',
      'VlrSeguroMensal2',
      'VlrServTerceiro',
      'VlrTxAdmMensal',
      'VlrVistoria',
    ],
  },

  manual: {
    usarCampoPadrao: true,
    usarCalculo: false,
    lancamentoForaDto: true,
    pixPagamentoForaDto: true,
    contaPagamentoForaDto: true,
    incluir: [],
    remover: [
      'PercRetencao', 
      'VlrRetencao',
      'VlrRegistroCartorio',
      'VlrIOF',
      'VlrIOFAdicional',
      'PercIOF',
      'VlrEntrada',
      'VlrEntradaParcelada',
      'VlrEntradaTradeIn',
      'VlrDespesasAF',
      'VlrCorban',
    ],
  },

  manualSAC: {
    usarCalculo: false,
    usarCampoPadrao: true,
    lancamentoForaDto: true,
    pixPagamentoForaDto: true,
    contaPagamentoForaDto: true,
    incluir: [],
    remover: [],
  },

  simplificado: {
    usarCampoPadrao: true,
    usarCalculo: false,
    usarFinanAntigo: true,
    lancamentoForaDto: true,
    pixPagamentoForaDto: true,
    contaPagamentoForaDto: true,
    incluir: [],
    remover: [],
  },

  simplificadoSAC: {
    usarCampoPadrao: true,
    usarCalculo: false,
    lancamentoForaDto: true,
    pixPagamentoForaDto: true,
    contaPagamentoForaDto: true,
    incluir: [],
    remover: [],
  },

  simplificadoPrice: {
    usarCampoPadrao: true,
    usarCalculo: false,
    lancamentoForaDto: true,
    pixPagamentoForaDto: true,
    contaPagamentoForaDto: true,
    incluir: [],
    remover: [],
  },

  limiteEspecial: {
    usarCampoPadrao: true,
    usarCalculo: false,
    lancamentoForaDto: true,
    pixPagamentoForaDto: true,
    contaPagamentoForaDto: true,
    incluir: [],
    remover: [],
  }
}